name="aBir is a loser"
print(len(name))
print(name.endswith("bir"))#true if ends with bir
print(name.startswith("Sb"))#False if doesnt starts with Sb 
print(name.replace("loser", "winner"))#replaces the word
print(name.capitalize()) #only capitalizes the first letter of the string
print(name.title()) #Writes only the first letter of each word in uppercase like the title of any paragraph...
print(name.lower()) #lowers all the letters including 1st to last....
print(name.upper())#Writes all the letters in uppercase...
print(name.find("aBir"))#prints the index of the string for e.g index of aBir is 0 as a comes in the point 0....
