Marks=[]
m1=input("Obtained marks by the student: ")
Marks.append(m1)
m2=input("Obtained marks by the student: ")
Marks.append(m2)
m3=input("Obtained marks by the student: ")
Marks.append(m3)
m4=input("Obtained marks by the student: ")
Marks.append(m4)
m5=input("Obtained marks by the student: ")
Marks.append(m5)
m6=input("Obtained marks by the student: ")
Marks.append(m6)
Marks.sort()
print(Marks)